### ISSUE TITLE
Does it works on latest titanium sdk 12.2.1?

### ISSUE THREAD

**Issue by ottopic** [hansemannn/titanium-weather-kit#1]
I have tried to configure it but I get error

`[ERROR] TypeError: undefined is not a function (near '...WeatherKit.getWeather...')`

**Comment by hansemannn** [comment]
Hi there! There was an issue in the way the function is called, this is now fixed in the [1.0.0 stable version](https://github.com/hansemannn/titanium-weather-kit/releases/tag/v1.0.0) :-)
